### ISSUE TITLE
Perform grey scale conversion on an image

### ISSUE THREAD

**Issue by Scarabyte** [Scarabyte/SSW690-Project#19] opened 2018-09-08 14:22 UTC
To facilitate image processing, convert to gray scale. Apply Gaussian filter.

**Comment by Scarabyte** [comment] 2018-09-18 00:08
Should the "Gaussian filter" part be a separate issue? And would that be part of #16?

**Comment by bsapana** [comment] 2018-09-21 00:03
This seems like duplicate of #16.

**Comment by kroseberry13SIT** [comment] 2018-09-21 18:28
This is really, really simple. The processing function is given a frame to work with - calling .gray() on that frame object will return a gray scale image of that frame. This can get more complicated if we need to adjust the method by which the image is converted to gray scale.

**Comment by rakshithv** [comment] 2018-10-01 20:42
Keith added this functionality into the baseline code. This code was added to the master branch in commit b428e53

**Closed by rakshithv** 2018-10-01 20:42 UTC
Labels: offline, task
